name: Upload Python Package

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get install make build-essential pkg-config
        sudo apt-get install libopenjp2-7-dev
        wget https://poppler.freedesktop.org/poppler-23.08.0.tar.xz
        tar -xvf poppler-23.08.0.tar.xz
        cd poppler-23.08.0
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DTESTDATADIR=$PWD/testfiles -DENABLE_UNSTABLE_API_ABI_HEADERS=ON -DENABLE_BOOST=OFF ..
        make
        sudo make install
        sudo apt-get install python3-dev
        python -m pip install --upgrade pip
        python -m pip install virtualenv
    - name: Test
      run: make test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get install make build-essential poppler-utils pkg-config python3-dev pdftohtml
        python -m pip install --upgrade pip
        python -m pip install virtualenv
    - name: Build package
      run: make build_dist
    - name: Publish package
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
